repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=10000']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-json
      - id: check-docstring-first
      - id: debug-statements
      - id: requirements-txt-fixer

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3
        exclude: ^(mathematics_dataset/|.*\.egg-info/|build/|dist/|\.venv/|venv/|env/|__pycache__/|\.pytest_cache/|\.ipynb_checkpoints/|notebooks/)

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: ^(mathematics_dataset/|.*\.egg-info/|build/|dist/|\.venv/|venv/|env/|__pycache__/|\.pytest_cache/|\.ipynb_checkpoints/|notebooks/)

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        exclude: ^(mathematics_dataset/|.*\.egg-info/|build/|dist/|\.venv/|venv/|env/|__pycache__/|\.pytest_cache/|\.ipynb_checkpoints/|notebooks/)

  - repo: https://github.com/pycqa/autoflake
    rev: v2.2.0
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --expand-star-imports
          - --ignore-init-module-imports
        exclude: ^(mathematics_dataset/|.*\.egg-info/|build/|dist/|\.venv/|venv/|env/|__pycache__/|\.pytest_cache/|\.ipynb_checkpoints/|notebooks/)

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]
        exclude: ^(mathematics_dataset/|.*\.egg-info/|build/|dist/|\.venv/|venv/|env/|__pycache__/|\.pytest_cache/|\.ipynb_checkpoints/|notebooks/) 